version: '3.8'

services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_DB: PintAndPillage
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  spring-backend:
    container_name: spring-backend
    build: ./PintAndPillageJavaBackend
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/PintAndPillage
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect
      SPRING_JPA_HIBERNATE_DDL_AUTO: create-drop
      SERVER_ERROR_INCLUDE_MESSAGE: always
      JWT_SECRET: super_secret_key_22228!

  vue-frontend:
    container_name: vue-frontend
    build:
      context: ./PintAndPillageFrontend
      dockerfile: Dockerfile
      args:
        BACKEND_URL: http://spring-backend:8080
    environment:
      - BACKEND_URL=http://spring-backend:8080
    ports:
      - "8080:8080"
    depends_on:
      - spring-backend